name: build
on:
  release:
    types: [published]

jobs:
  publish:
    name: build

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      # install bun binaries
      - name: install bun
        # uses: oven-sh/setup-bun@v1
        # with:
        #   bun-version: 1
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: source binary
        shell: bash
        run: |
          source /home/runner/.bashrc

      - name: setup bun PATH
        shell: bash
        run: |
          echo PATH=/home/runner/.bun/bin/bun >> $GITHUB_PATH

      - name: install dependencies
        run:  /home/runner/.bun/bin/bun install

      - name: build package
        run:  /home/runner/.bun/bin/bun build.ts
      # - name: run test suites
      #   run: npm test

      - name: publish
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}